apiVersion: v1
kind: Secret
metadata:
  name: mysecret1
type: Opaque
stringData: # store the string as base64
  username: admin
  password: "12345678"
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: nginx:alpine
    volumeMounts:
      - mountPath: "/opt"
        name: test
        readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  volumes:
    - name: test
      secret:
        secretName: mysecret1
        items:
        - key: username
          path: user.txt
        - key: password
          path: password.txt 
