apiVersion: v1
kind: Namespace
metadata:
  name: ci
  labels:
    name: ci
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-k8s-hands-on
  namespace: ci
  labels:
    app: backend
spec:
#   revisionHistoryLimit: 1
  replicas: 3
  selector: 
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: k8s-hands-on:v2
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  namespace: ci
  name: backend-k8s-hands-on
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

