apiVersion: v1
kind: Namespace
metadata:
  name: qa
  labels:
    name: qa
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: res-quota-pod
  namespace: qa
spec:
  hard:
    pods: "3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-qa
  namespace: qa
  labels:
    app: front
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests: 
            memory: 500M
            cpu: 500m
          limits:
            memory: 500M
            cpu: 500m