apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /var/log/nginx
        name: vol
    ports:
      - containerPort: 8080
  volumes:
    - name: vol
      emptyDir: {}
        
